### PR TITLE
Re: Page in between redirection 

### PR DESCRIPTION
**Pull request by SteakFisher**
No dependencies added whatsoever this time, and no issues running locally, I apologize for being a moron last time
Also if u dont mind can u also mark iiitv/algos-web#80 as a contribut-a-thon issue

### CODE REVIEW

**Comment by SteakFisher** [comment]
Apparently useEffect dependencies don't cause errors locally, but they do in production.. I.. cool

**Comment by AniModi** [comment]
> Apparently useEffect dependencies don't cause errors locally, but they do in production.. I.. cool

Actually, when you miss some dependencies in useEffect, they show up as warnings in terminal. In local host, it is fine and we can ignore them. But during deploy on Netlify, it treats the warnings as errors by default.

**Comment by AniModi** [comment]
LGTM!

**Review by AniModi — COMMENTED** [review]
Merged.

**Pull request merged**
