### PR TITLE
testing auto-deployment with now

### PR DESCRIPTION
**Pull request by mohitkyadav**
Set up auto deploy pull request on zeit.co

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
You sure we are going with now and not traditional react-gh-pages?

**Comment by mohitkyadav** [comment]
@aashutoshrathi no, just so that every time someone sends a PR we don't have to pull and run to see the changes. Every PR will be auto deployed using *now* and you can see what's the change in your browser.

**Comment by aashutoshrathi** [comment]
@mohitkyadav Is this PR deployed somewhere too?

**Comment by mohitkyadav** [comment]
https://zeit.co/github/deployment?deploymentId=DOlAedLjhL2LWzWySjRgElTU

**Comment by mohitkyadav** [comment]
Better than **now**. 😆

**Comment by anshumanv** [comment]
Closing in favour of https://github.com/iiitv/algos-web/pull/11#issuecomment-602262153

Now never happened 😕

**Pull request closed without merging**
